language: java
notifications:
  email: false
if: tag IS blank

before_install: chmod +x gradlew
install: "./gradlew"
script: "./gradlew build --stacktrace --info"
jdk:
  - openjdk8
before_cache:
  - find $HOME/.gradle/ -name '*.lock' -print -exec rm -f {} \;
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
sudo: false

before_deploy:
  - export RELEASE_FILE_LIST=$(ls ./build/libs/* | tr '\n' ', ')
  - echo "deploying $RELEASE_FILE_LIST to GitHub releases"
deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$TOKEN"
  file_glob: true
  file: "{$RELEASE_FILE_LIST}"
  on:
    repo: Cryptic-Mushroom/Iron-Dimension-Revised
    branch: fabric
    tags: false
